import type { GeoPoint } from './globe-geography';

export interface VerifiedUniversityLocation extends GeoPoint {
  city: string;
  countryCode: string;
  locationLabel: string;
  sourceLabel: string;
  sourceUrl: string;
  coordinateType?: 'campus' | 'city-fallback';
  imageUrl?: string;
  logoUrl?: string;
  rankingSource?: string;
  rankingCategory?: string;
  rankingYear?: number;
  rankingRank?: number;
}

const entries: Array<[string, VerifiedUniversityLocation]> = [
  [
    'TR:ACIBADEM MEHMET ALI AYDINLAR UNIVERSITY',
    {
      countryCode: 'TR',
      city: 'Istanbul',
      lat: 40.9253,
      lng: 29.1544,
      locationLabel: 'Kerem Aydinlar Campus, Atasehir, Istanbul',
      sourceLabel: 'Official campus address; coordinates verified from map listing',
      sourceUrl: 'https://prod.acibadem.edu.tr/kayit/iletisim/ulasim',
      logoUrl: 'https://www.acibadem.edu.tr/sites/default/files/2025-04/acu_logo.svg',
    },
  ],
  [
    'TR:ANKARA UNIVERSITY',
    {
      countryCode: 'TR',
      city: 'Ankara',
      lat: 39.93000831907095,
      lng: 32.85866413122493,
      locationLabel: 'Faculty of Medicine Morphology Campus, Altindag, Ankara',
      sourceLabel: 'Official Faculty of Medicine campus map',
      sourceUrl: 'https://www.medicine.ankara.edu.tr/en/campuses/',
      logoUrl:
        'https://www.medicine.ankara.edu.tr/wp-content/uploads/sites/121/2018/06/medicinelogo.png',
    },
  ],
  [
    'TR:KOC UNIVERSITY',
    {
      countryCode: 'TR',
      city: 'Istanbul',
      lat: 41.20586,
      lng: 29.0752,
      locationLabel: 'Rumelifeneri Campus, Sariyer, Istanbul',
      sourceLabel: 'Official campus address; coordinates verified from map listing',
      sourceUrl: 'https://www.ku.edu.tr/iletisim/kampuslerimiz/rumelifeneri-kampusu/',
      logoUrl: 'https://www.ku.edu.tr/wp-content/uploads/2023/09/logo-renkli.png',
    },
  ],
  [
    'TR:HACETTEPE UNIVERSITY',
    {
      countryCode: 'TR',
      city: 'Ankara',
      lat: 39.93179163888889,
      lng: 32.8626833,
      locationLabel: 'Faculty of Medicine, Sihhiye Campus, Ankara',
      sourceLabel: 'Official campus contact; coordinates verified from Wikidata',
      sourceUrl: 'https://hacettepe.edu.tr/about/contact',
    },
  ],
  [
    'TR:ISTANBUL UNIVERSITY-CERRAHPASA',
    {
      countryCode: 'TR',
      city: 'Istanbul',
      lat: 41.005672,
      lng: 28.940349,
      locationLabel: 'Cerrahpasa Faculty of Medicine Campus, Fatih, Istanbul',
      sourceLabel: 'Official faculty address; coordinates verified from map listing',
      sourceUrl: 'https://cerrahpasatiptanitim.iuc.edu.tr/',
      logoUrl: 'https://cerrahpasatiptanitim.iuc.edu.tr/assets/images/logo/ctf-logo.png',
    },
  ],

  // GEORGIA (GE) - Verified Campus Locations
  [
    'GE:TBILISI STATE MEDICAL UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.7289,
      lng: 44.7570,
      locationLabel: '33 Vazha-Pshavela Ave, Saburtalo, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://tsmu.edu',
    },
  ],
  [
    'GE:DAVID TVILDIANI MEDICAL UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.7772,
      lng: 44.7663,
      locationLabel: '2/6 Ljubljana St, Dighomi, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://dtmu.ge',
    },
  ],
  [
    'GE:EAST EUROPEAN UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.7946,
      lng: 44.7892,
      locationLabel: '4 I. Enukidze St, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://eeu.edu.ge',
    },
  ],
  [
    'GE:NEW VISION UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.7583,
      lng: 44.7672,
      locationLabel: '1a Evgeni Mikeladze St, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://newvision.ge',
    },
  ],
  [
    'GE:GEORGIAN NATIONAL UNIVERSITY SEU',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.6917,
      lng: 44.8291,
      locationLabel: '9 Tsinandali St, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://seu.edu.ge',
    },
  ],
  [
    'GE:ILIA STATE UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.7128,
      lng: 44.7638,
      locationLabel: '3/5 Kakutsa Cholokhashvili Ave, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://iliauni.edu.ge',
    },
  ],
  [
    'GE:UNIVERSITY OF GEORGIA',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.7208,
      lng: 44.7734,
      locationLabel: '77a Merab Kostava St, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://ug.edu.ge',
    },
  ],
  [
    'GE:PETRE SHOTADZE TBILISI MEDICAL ACADEMY',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.6923,
      lng: 44.8368,
      locationLabel: '51/2 Ketevan Tsamebuli Ave, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://tma.edu.ge',
    },
  ],
  [
    'GE:GEORGIAN AMERICAN UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.7169,
      lng: 44.7850,
      locationLabel: '10 Merab Aleksidze St, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://gau.edu.ge',
    },
  ],
  [
    'GE:CAUCASUS INTERNATIONAL UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.7694,
      lng: 44.8083,
      locationLabel: '73 Chargali St, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://ciu.edu.ge',
    },
  ],
  [
    'GE:ALTE UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.7197,
      lng: 44.7431,
      locationLabel: '3 University St, Saburtalo, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://alte.edu.ge',
    },
  ],
  [
    'GE:IVANE JAVAKHISHVILI TBILISI STATE UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.7103,
      lng: 44.7775,
      locationLabel: '1 Ilia Chavchavadze Ave, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://tsu.ge',
    },
  ],
  [
    'GE:EUROPEAN UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.7770,
      lng: 44.8105,
      locationLabel: '76 Guramishvili Ave, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://eu.edu.ge',
    },
  ],
  [
    'GE:GRIGOL ROBAKIDZE UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Tbilisi',
      lat: 41.7917,
      lng: 44.7778,
      locationLabel: '13 David Aghmashenebeli Alley, Tbilisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://gruni.edu.ge',
    },
  ],
  [
    'GE:BATUMI SHOTA RUSTAVELI STATE UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Batumi',
      lat: 41.6508,
      lng: 41.6339,
      locationLabel: '35 Ninoshvili St, Batumi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://bsu.edu.ge',
    },
  ],
  [
    'GE:BAU INTERNATIONAL UNIVERSITY BATUMI',
    {
      countryCode: 'GE',
      city: 'Batumi',
      lat: 41.6033,
      lng: 41.6142,
      locationLabel: '237 Fridon Khalvashi Ave, Batumi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://bauinternational.edu.ge',
    },
  ],
  [
    'GE:AVICENNA BATUMI MEDICAL UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Batumi',
      lat: 41.6342,
      lng: 41.6156,
      locationLabel: '120 Tbel Abuseridze St, Batumi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://avicenna.ge',
    },
  ],
  [
    'GE:AKAKI TSERETELI STATE UNIVERSITY',
    {
      countryCode: 'GE',
      city: 'Kutaisi',
      lat: 42.2614,
      lng: 42.7058,
      locationLabel: '59 Tamar Mefe St, Kutaisi',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://atsu.edu.ge',
    },
  ],

  // KAZAKHSTAN (KZ) - Verified Campus Locations
  [
    'KZ:S.D. ASFENDIYAROV KAZAKH NATIONAL MEDICAL UNIVERSITY',
    {
      countryCode: 'KZ',
      city: 'Almaty',
      lat: 43.2547,
      lng: 76.9317,
      locationLabel: '94 Tole Bi St, Almaty',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://kaznmu.edu.kz',
    },
  ],
  [
    'KZ:AL-FARABI KAZAKH NATIONAL UNIVERSITY',
    {
      countryCode: 'KZ',
      city: 'Almaty',
      lat: 43.2241,
      lng: 76.9208,
      locationLabel: '71 al-Farabi Ave, Almaty',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://kaznu.kz',
    },
  ],
  [
    'KZ:KAZAKH-RUSSIAN MEDICAL UNIVERSITY',
    {
      countryCode: 'KZ',
      city: 'Almaty',
      lat: 43.2647,
      lng: 76.9542,
      locationLabel: '71 Torekulov St, Almaty',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://krmu.edu.kz',
    },
  ],
  [
    'KZ:CASPIAN UNIVERSITY',
    {
      countryCode: 'KZ',
      city: 'Almaty',
      lat: 43.2575,
      lng: 76.9389,
      locationLabel: '521 Seifullin Ave, Almaty',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://caspian.edu.kz',
    },
  ],
  [
    'KZ:KENZHEGALI SAGADIYEV UNIVERSITY OF INTERNATIONAL BUSINESS',
    {
      countryCode: 'KZ',
      city: 'Almaty',
      lat: 43.2411,
      lng: 76.9531,
      locationLabel: '8A Abay Ave, Almaty',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://uib.edu.kz',
    },
  ],
  [
    'KZ:ASTANA MEDICAL UNIVERSITY',
    {
      countryCode: 'KZ',
      city: 'Astana',
      lat: 51.1719,
      lng: 71.4161,
      locationLabel: '49/1 Beybitshilik St, Astana',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://amu.edu.kz',
    },
  ],
  [
    'KZ:WEST KAZAKHSTAN MARAT OSPANOV MEDICAL UNIVERSITY',
    {
      countryCode: 'KZ',
      city: 'Aktobe',
      lat: 50.2975,
      lng: 57.1539,
      locationLabel: '68 Maresyev St, Aktobe',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://zkgmu.kz',
    },
  ],
  [
    'KZ:SEMEY MEDICAL UNIVERSITY',
    {
      countryCode: 'KZ',
      city: 'Semey',
      lat: 50.4114,
      lng: 80.2522,
      locationLabel: '103 Abay Kunanbayev St, Semey',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://smu.edu.kz',
    },
  ],
  [
    'KZ:KARAGANDA MEDICAL UNIVERSITY',
    {
      countryCode: 'KZ',
      city: 'Karaganda',
      lat: 49.8064,
      lng: 73.0856,
      locationLabel: '40 Gogol St, Karaganda',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://qmu.edu.kz',
    },
  ],
  [
    'KZ:SOUTH KAZAKHSTAN MEDICAL ACADEMY',
    {
      countryCode: 'KZ',
      city: 'Shymkent',
      lat: 42.3178,
      lng: 69.5892,
      locationLabel: '1 Al-Farabi Square, Shymkent',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://skma.kz',
    },
  ],

  // HUNGARY (HU) - Verified Campus Locations
  [
    'HU:SEMMELWEIS UNIVERSITY',
    {
      countryCode: 'HU',
      city: 'Budapest',
      lat: 47.4875,
      lng: 19.0683,
      locationLabel: 'Üllői út 26, Budapest',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://semmelweis.hu',
    },
  ],
  [
    'HU:UNIVERSITY OF DEBRECEN',
    {
      countryCode: 'HU',
      city: 'Debrecen',
      lat: 47.5544,
      lng: 21.6231,
      locationLabel: 'Egyetem tér 1, Debrecen',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://unideb.hu',
    },
  ],
  [
    'HU:UNIVERSITY OF SZEGED',
    {
      countryCode: 'HU',
      city: 'Szeged',
      lat: 46.2519,
      lng: 20.1444,
      locationLabel: 'Dugonics tér 13, Szeged',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://u-szeged.hu',
    },
  ],
  [
    'HU:UNIVERSITY OF PECS',
    {
      countryCode: 'HU',
      city: 'Pécs',
      lat: 46.0747,
      lng: 18.2328,
      locationLabel: '48-as tér 1, Pécs',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://pte.hu',
    },
  ],

  // AUSTRALIA (AU) - Verified Campus Locations
  [
    'AU:UNIVERSITY OF SYDNEY',
    {
      countryCode: 'AU',
      city: 'Sydney',
      lat: -33.8886,
      lng: 151.1873,
      locationLabel: 'Camperdown, Sydney, New South Wales',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://sydney.edu.au',
    },
  ],
  [
    'AU:UNIVERSITY OF NEW SOUTH WALES',
    {
      countryCode: 'AU',
      city: 'Sydney',
      lat: -33.9173,
      lng: 151.2313,
      locationLabel: 'Kensington, Sydney, New South Wales',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://unsw.edu.au',
    },
  ],
  [
    'AU:WESTERN SYDNEY UNIVERSITY',
    {
      countryCode: 'AU',
      city: 'Campbelltown',
      lat: -34.0744,
      lng: 150.7933,
      locationLabel: 'Narellan Rd, Campbelltown, New South Wales',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://westernsydney.edu.au',
    },
  ],
  [
    'AU:MONASH UNIVERSITY',
    {
      countryCode: 'AU',
      city: 'Clayton',
      lat: -37.9105,
      lng: 145.1362,
      locationLabel: 'Wellington Rd, Clayton, Melbourne, Victoria',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://monash.edu',
    },
  ],
  [
    'AU:UNIVERSITY OF QUEENSLAND',
    {
      countryCode: 'AU',
      city: 'Brisbane',
      lat: -27.4975,
      lng: 153.0137,
      locationLabel: 'St Lucia, Brisbane, Queensland',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://uq.edu.au',
    },
  ],
  [
    'AU:ADELAIDE UNIVERSITY',
    {
      countryCode: 'AU',
      city: 'Adelaide',
      lat: -34.9205,
      lng: 138.6053,
      locationLabel: 'North Terrace, Adelaide, South Australia',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://adelaide.edu.au',
    },
  ],
  [
    'AU:UNIVERSITY OF WESTERN AUSTRALIA',
    {
      countryCode: 'AU',
      city: 'Perth',
      lat: -31.9804,
      lng: 115.8183,
      locationLabel: 'Crawley, Perth, Western Australia',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://uwa.edu.au',
    },
  ],
  [
    'AU:CURTIN UNIVERSITY',
    {
      countryCode: 'AU',
      city: 'Perth',
      lat: -32.0044,
      lng: 115.8947,
      locationLabel: 'Kent St, Bentley, Perth, Western Australia',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://curtin.edu.au',
    },
  ],

  // RUSSIA (RU) - Verified Campus Locations
  [
    'RU:I.M. SECHENOV FIRST MOSCOW STATE MEDICAL UNIVERSITY',
    {
      countryCode: 'RU',
      city: 'Moscow',
      lat: 55.7289,
      lng: 37.5750,
      locationLabel: 'Trubetskaya St 8, Moscow',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://sechenov.ru',
    },
  ],
  [
    'RU:PIROGOV RUSSIAN NATIONAL RESEARCH MEDICAL UNIVERSITY',
    {
      countryCode: 'RU',
      city: 'Moscow',
      lat: 55.6428,
      lng: 37.5028,
      locationLabel: 'Ostrovityanova St 1, Moscow',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://rsmu.ru',
    },
  ],
  [
    'RU:PEOPLES FRIENDSHIP UNIVERSITY OF RUSSIA (RUDN)',
    {
      countryCode: 'RU',
      city: 'Moscow',
      lat: 55.6514,
      lng: 37.5042,
      locationLabel: 'Miklukho-Maklaya St 6, Moscow',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://rudn.ru',
    },
  ],
  [
    'RU:ST. PETERSBURG STATE PEDIATRIC MEDICAL UNIVERSITY',
    {
      countryCode: 'RU',
      city: 'Saint Petersburg',
      lat: 59.9767,
      lng: 30.3456,
      locationLabel: 'Litovskaya St 2, Saint Petersburg',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://gpmu.org',
    },
  ],
  [
    'RU:ST. PETERSBURG STATE UNIVERSITY',
    {
      countryCode: 'RU',
      city: 'Saint Petersburg',
      lat: 59.9419,
      lng: 30.3047,
      locationLabel: 'Universitetskaya Emb 7/9, Saint Petersburg',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://spbu.ru',
    },
  ],
  [
    'RU:KAZAN STATE MEDICAL UNIVERSITY',
    {
      countryCode: 'RU',
      city: 'Kazan',
      lat: 55.7878,
      lng: 49.1389,
      locationLabel: 'Butlerov St 49, Kazan, Tatarstan',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://kazangmu.ru',
    },
  ],
  [
    'RU:KAZAN FEDERAL UNIVERSITY',
    {
      countryCode: 'RU',
      city: 'Kazan',
      lat: 55.7906,
      lng: 49.1219,
      locationLabel: 'Kremlyovskaya St 18, Kazan, Tatarstan',
      sourceLabel: 'Official campus address; coordinates verified from official registry',
      sourceUrl: 'https://kpfu.ru',
    },
  ],

  // INDIA (IN) - Verified Medical Institution Campus Locations (NIRF Medical Rankings 2024)
  [
    'IN:AIIMS NEW DELHI',
    {
      countryCode: 'IN',
      city: 'New Delhi',
      lat: 28.5672,
      lng: 77.2100,
      locationLabel: 'Ansari Nagar, Sri Aurobindo Marg, New Delhi, Delhi - 110029',
      sourceLabel: 'Official campus address; coordinates verified from AIIMS administrative campus',
      sourceUrl: 'https://www.aiims.edu',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 1,
    },
  ],
  [
    'IN:ALL INDIA INSTITUTE OF MEDICAL SCIENCES',
    {
      countryCode: 'IN',
      city: 'New Delhi',
      lat: 28.5672,
      lng: 77.2100,
      locationLabel: 'Ansari Nagar, Sri Aurobindo Marg, New Delhi, Delhi - 110029',
      sourceLabel: 'Official campus address; coordinates verified from AIIMS administrative campus',
      sourceUrl: 'https://www.aiims.edu',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 1,
    },
  ],
  [
    'IN:PGIMER CHANDIGARH',
    {
      countryCode: 'IN',
      city: 'Chandigarh',
      lat: 30.7638,
      lng: 76.7820,
      locationLabel: 'Sector 12, Madhya Marg, Chandigarh - 160012',
      sourceLabel: 'Official campus address; coordinates verified from PGIMER Sector 12 campus',
      sourceUrl: 'https://pgimer.edu.in',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 2,
    },
  ],
  [
    'IN:POSTGRADUATE INSTITUTE OF MEDICAL EDUCATION & RESEARCH',
    {
      countryCode: 'IN',
      city: 'Chandigarh',
      lat: 30.7638,
      lng: 76.7820,
      locationLabel: 'Sector 12, Madhya Marg, Chandigarh - 160012',
      sourceLabel: 'Official campus address; coordinates verified from PGIMER Sector 12 campus',
      sourceUrl: 'https://pgimer.edu.in',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 2,
    },
  ],
  [
    'IN:CMC VELLORE',
    {
      countryCode: 'IN',
      city: 'Vellore',
      lat: 12.9248,
      lng: 79.1350,
      locationLabel: 'Ida Scudder Road, Vellore, Tamil Nadu - 632004',
      sourceLabel: 'Official campus address; coordinates verified from CMC Hospital & Medical College campus',
      sourceUrl: 'https://www.cmch-vellore.edu',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 3,
    },
  ],
  [
    'IN:CHRISTIAN MEDICAL COLLEGE',
    {
      countryCode: 'IN',
      city: 'Vellore',
      lat: 12.9248,
      lng: 79.1350,
      locationLabel: 'Ida Scudder Road, Vellore, Tamil Nadu - 632004',
      sourceLabel: 'Official campus address; coordinates verified from CMC Hospital & Medical College campus',
      sourceUrl: 'https://www.cmch-vellore.edu',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 3,
    },
  ],
  [
    'IN:NIMHANS BENGALURU',
    {
      countryCode: 'IN',
      city: 'Bengaluru',
      lat: 12.9431,
      lng: 77.5960,
      locationLabel: 'Hosur Road, Lakkasandra, Bengaluru, Karnataka - 560029',
      sourceLabel: 'Official campus address; coordinates verified from NIMHANS main campus, Hosur Rd',
      sourceUrl: 'https://nimhans.ac.in',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 4,
    },
  ],
  [
    'IN:NATIONAL INSTITUTE OF MENTAL HEALTH & NEUROSCIENCES',
    {
      countryCode: 'IN',
      city: 'Bengaluru',
      lat: 12.9431,
      lng: 77.5960,
      locationLabel: 'Hosur Road, Lakkasandra, Bengaluru, Karnataka - 560029',
      sourceLabel: 'Official campus address; coordinates verified from NIMHANS main campus, Hosur Rd',
      sourceUrl: 'https://nimhans.ac.in',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 4,
    },
  ],
  [
    'IN:JIPMER PUDUCHERRY',
    {
      countryCode: 'IN',
      city: 'Puducherry',
      lat: 11.9567,
      lng: 79.7997,
      locationLabel: 'Jipmer Campus Road, Gorimedu, Puducherry - 605006',
      sourceLabel: 'Official campus address; coordinates verified from JIPMER Gorimedu campus',
      sourceUrl: 'https://jipmer.edu.in',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 5,
    },
  ],
  [
    'IN:JAWAHARLAL INSTITUTE OF POSTGRADUATE MEDICAL EDUCATION & RESEARCH',
    {
      countryCode: 'IN',
      city: 'Puducherry',
      lat: 11.9567,
      lng: 79.7997,
      locationLabel: 'Jipmer Campus Road, Gorimedu, Puducherry - 605006',
      sourceLabel: 'Official campus address; coordinates verified from JIPMER Gorimedu campus',
      sourceUrl: 'https://jipmer.edu.in',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 5,
    },
  ],
  [
    'IN:AMRITA VISHWA VIDYAPEETHAM SCHOOL OF MEDICINE',
    {
      countryCode: 'IN',
      city: 'Kochi',
      lat: 10.0334,
      lng: 76.2974,
      locationLabel: 'AIMS Ponekkara P.O., Edappally, Kochi, Kerala - 682041',
      sourceLabel: 'Official campus address; coordinates verified from Amrita Health Sciences campus, Kochi',
      sourceUrl: 'https://www.amrita.edu/school/medicine/',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 6,
    },
  ],
  [
    'IN:AMRITA INSTITUTE OF MEDICAL SCIENCES',
    {
      countryCode: 'IN',
      city: 'Kochi',
      lat: 10.0334,
      lng: 76.2974,
      locationLabel: 'AIMS Ponekkara P.O., Edappally, Kochi, Kerala - 682041',
      sourceLabel: 'Official campus address; coordinates verified from Amrita Health Sciences campus, Kochi',
      sourceUrl: 'https://www.amrita.edu/school/medicine/',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 6,
    },
  ],
  [
    'IN:SGPGI LUCKNOW',
    {
      countryCode: 'IN',
      city: 'Lucknow',
      lat: 26.7490,
      lng: 80.9392,
      locationLabel: 'Raebareli Road, Telibagh, Lucknow, Uttar Pradesh - 226014',
      sourceLabel: 'Official campus address; coordinates verified from SGPGI main campus, Raebareli Rd',
      sourceUrl: 'https://sgpgims.org.in',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 7,
    },
  ],
  [
    'IN:SANJAY GANDHI POSTGRADUATE INSTITUTE OF MEDICAL SCIENCES',
    {
      countryCode: 'IN',
      city: 'Lucknow',
      lat: 26.7490,
      lng: 80.9392,
      locationLabel: 'Raebareli Road, Telibagh, Lucknow, Uttar Pradesh - 226014',
      sourceLabel: 'Official campus address; coordinates verified from SGPGI main campus, Raebareli Rd',
      sourceUrl: 'https://sgpgims.org.in',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 7,
    },
  ],
  [
    'IN:BHU INSTITUTE OF MEDICAL SCIENCES',
    {
      countryCode: 'IN',
      city: 'Varanasi',
      lat: 25.2758,
      lng: 82.9996,
      locationLabel: 'Banaras Hindu University Campus, Varanasi, Uttar Pradesh - 221005',
      sourceLabel: 'Official campus address; coordinates verified from IMS BHU campus, Varanasi',
      sourceUrl: 'https://new.bhu.ac.in/Site/UnitHome/ims',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 8,
    },
  ],
  [
    'IN:INSTITUTE OF MEDICAL SCIENCES, BHU',
    {
      countryCode: 'IN',
      city: 'Varanasi',
      lat: 25.2758,
      lng: 82.9996,
      locationLabel: 'Banaras Hindu University Campus, Varanasi, Uttar Pradesh - 221005',
      sourceLabel: 'Official campus address; coordinates verified from IMS BHU campus, Varanasi',
      sourceUrl: 'https://new.bhu.ac.in/Site/UnitHome/ims',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 8,
    },
  ],
  [
    'IN:KASTURBA MEDICAL COLLEGE, MANIPAL',
    {
      countryCode: 'IN',
      city: 'Manipal',
      lat: 13.3533,
      lng: 74.7865,
      locationLabel: 'Tiger Circle Road, Madhav Nagar, Manipal, Karnataka - 576104',
      sourceLabel: 'Official campus address; coordinates verified from KMC Madhav Nagar campus, Manipal',
      sourceUrl: 'https://manipal.edu/kmc-manipal.html',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 9,
    },
  ],
  [
    'IN:KMC MANIPAL',
    {
      countryCode: 'IN',
      city: 'Manipal',
      lat: 13.3533,
      lng: 74.7865,
      locationLabel: 'Tiger Circle Road, Madhav Nagar, Manipal, Karnataka - 576104',
      sourceLabel: 'Official campus address; coordinates verified from KMC Madhav Nagar campus, Manipal',
      sourceUrl: 'https://manipal.edu/kmc-manipal.html',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 9,
    },
  ],
  [
    'IN:KING GEORGE\'S MEDICAL UNIVERSITY',
    {
      countryCode: 'IN',
      city: 'Lucknow',
      lat: 26.8687,
      lng: 80.9168,
      locationLabel: 'Shah Mina Road, Chowk, Lucknow, Uttar Pradesh - 226003',
      sourceLabel: 'Official campus address; coordinates verified from KGMU Chowk campus, Lucknow',
      sourceUrl: 'https://kgmu.org',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 10,
    },
  ],
  [
    'IN:KGMU',
    {
      countryCode: 'IN',
      city: 'Lucknow',
      lat: 26.8687,
      lng: 80.9168,
      locationLabel: 'Shah Mina Road, Chowk, Lucknow, Uttar Pradesh - 226003',
      sourceLabel: 'Official campus address; coordinates verified from KGMU Chowk campus, Lucknow',
      sourceUrl: 'https://kgmu.org',
      coordinateType: 'campus',
      rankingSource: 'NIRF',
      rankingCategory: 'Medical',
      rankingYear: 2024,
      rankingRank: 10,
    },
  ],
];

export const VERIFIED_UNIVERSITY_LOCATIONS = entries;

const locations = new Map<string, VerifiedUniversityLocation>(
  entries.map(([key, value]) => [normalizeUniversityKey(key), value]),
);

export function verifiedUniversityLocation(
  countryCode: string,
  universityName: string,
): VerifiedUniversityLocation | null {
  return locations.get(normalizeUniversityKey(`${countryCode}:${universityName}`)) ?? null;
}

function normalizeUniversityKey(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[ıİ]/g, 'I')
    .replace(/\s+/g, ' ')
    .trim()
    .toUpperCase();
}
